### PR TITLE
Add Mod10Check and Mod11Check support

### LINKED ISSUE #567: Add support for `Mod10Check` Hibernate annotation
### Feature description

>  Allows to validate that a series of digits pass the Mod10 checksum algorithm. The classic Mod10 is calculated by summing up the digits, with every odd digit (from right to left) value multiplied by a multiplier. As example ISBN-13 is Modulo 10 checksum with multiplier = 3.
>
> There are known cases of codes using multipliers for both even and odd digits; To support this kind of implementations the Mod10 constraint uses the weight option, which has the same effect as the multiplier but for even numbers.
>
> The supported type is CharSequence. null is considered valid. 

Source: https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/Mod10Check.html

Since this annotation is available in Hibernate Validator 5, test cases should be included in both:

- `bean-validation-hibernate-tests`
- `bean-validation-hibernate5-tests`

### LINKED ISSUE #568: Add support for `Mod11Check` Hibernate annotation
### Feature description

> Modulo 11 check constraint.
>
> Allows to validate that a series of digits passes the Mod11 checksum algorithm. For the most common Mod11 variant the sum calculation is done by multiplying a weight from the rightmost digit (excluding the check digit) to the leftmost. The weight starts with 2 and increases by 1 for each digit. Then the result is used to calculate the check digit using 11 - ( sum % 11 ).
> 
> Example: The check digit for 24187 is 3
> Sum = 7x2 + 8x3 + 1x4 + 4x5 + 2x6 = 74
> 11 - (74 % 11) = 11 - 8 = 3, so "24187-3" is a valid character sequence.
> 
> The Mod11 calculation can result in 10 or 11; per default 10 is treated as 'X' and 11 as '0', this behavior can be changed using the options treatCheck10As and treatCheck10As.
> 
> Some implementations do the sum calculation in the reverse order (left to right); specify the processing direction [Mod11Check.ProcessingDirection.LEFT_TO_RIGHT](https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/Mod11Check.ProcessingDirection.html#LEFT_TO_RIGHT) in this case.
> 
> The supported type is CharSequence. null is considered valid.

Source: https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/Mod11Check.html

Since this annotation is available in Hibernate Validator 5, test cases should be included in both:

- `bean-validation-hibernate-tests`
- `bean-validation-hibernate5-tests`

### PR DESCRIPTION
**Pull request by EvaristeGalois11**
Close #567, Close #568 

Hi,
I introduced support for `Mod11Check` and `Mod10Check` alongside a general refactor of the preexisting module based generators. I'm not a big fan of the base class that does everything approach, but given the sheer amount of parameters that the module formula required just a static method wasn't enough. All in all it isn't that terrible I think.

I'm still reviewing if something could be refactored and redone a little better, but given that four eyes see more than two I'm opening the PR already so you can start reviewing it too :D

Bye!

### CODE REVIEW

**Comment by armandino** [comment]
Thank you for the PR, @EvaristeGalois11! I don't have much to add other than a couple of nitpicks. Looks great!

**Comment by armandino** [comment]
@EvaristeGalois11 I'll go ahead and merge your changes. No worries about the comments. Those are just minor things I can update later. Thank you again for the PR.

**Comment by EvaristeGalois11** [comment]
Thanks for the merge :D

As an unrelated note, if you have some more stuff in mind to do around the project feel free to open them as up-for-grabs. I'm a bit busy at the moment, but I'll gladly help if I can (i'm planning to tackle the optional ones as soon as I have some time to focus on them).

**Comment by armandino** [comment]
Sounds good, thank you for the offer. Very much appreciated!

**Pull request merged**
