### PR TITLE
Use sonar-fork-analysis action

### LINKED ISSUE #783: Build workflow - Sonar scans of PRs from forks affect `main` branch
Sonar analysis is not officially supported on PRs from forks, but it can be achieved with workarounds:

- https://community.sonarsource.com/t/sonar-cannot-be-run-on-pr-from-a-fork/69229
- https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363/34

This was implemented in #540. The works well, however, one of the side effects is that when the analysis is done on a PR from a fork, it affects the quality gate and test coverage of the `main` branch:

image

<br><br>
The PR results are then displayed via badges on the main page:

image

<br><br>
Ideally, the analysis of a PR should not affect the `main` branch.

### PR DESCRIPTION
**Pull request by EvaristeGalois11**
Hi, sorry it took so long but I finally found the time to look into the Sonar problem.

I ended up refactoring the majority of the hacky workarounds in a separate github action https://github.com/EvaristeGalois11/sonar-fork-analysis so it could be more easily reused.

This pull request will most likely fail because workflow of type `workflow_run` are taken from the default branch instead of the pull request one, but the fix should work fine after being merged.

Close #783

### CODE REVIEW

**Comment by armandino** [comment]
@EvaristeGalois11 that's amazing, thank you! Great idea to make it a reusable action. I think this will benefit a lot of other projects that use Sonar.

We'll need another PR to test it :)

**Review by armandino — APPROVED** [review]

**Comment by EvaristeGalois11** [comment]
Thank you @armandino, I'm planning to add gradle support too so it can be used by even more people :)

Do you mind if I reference instancio in the readme as a real life example of how to use the action with maven?

**Comment by armandino** [comment]
> Do you mind if I reference instancio in the readme as a real life example of how to use the action with maven?

Sure thing! I also wanted to mention it in this thread:

https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363/34

It's the one that always came up in my search when I was looking for a solution. If you don't mind, I'll post a reply there.

**Comment by EvaristeGalois11** [comment]
> Sure thing! I also wanted to mention it in this thread:
> 
> https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363/34
> 
> It's the one that always came up in my search when I was looking for a solution. If you don't mind, I'll post a reply there.

Oh that's a really great idea, thank you!

**Pull request merged**
