### PR TITLE
Small change to test GitHub workflow changes

### PR DESCRIPTION
**Pull request by armandino**
Issue #540

### CODE REVIEW

**Comment by EvaristeGalois11** [comment]
Almost there!

I think you should try putting back the `-Dsonar.projectKey=instancio_instancio` parameter to `mvn -B sonar:sonar` in the sonar.yml file.

I moved it to the pom.xml when i was tweking the workflow but i didn't know that it was there for a very good reason sorry.

**Comment by armandino** [comment]
@EvaristeGalois11 almost there. Just need to figure out the zip file contents and hopefully that'll be it.

> Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project instancio-parent: Your project contains .java files, please provide compiled classes with sonar.java.binaries property, or exclude them from the analysis with sonar.exclusions property.

**Comment by EvaristeGalois11** [comment]
Wow that's annoying lol

I can try uploading every target directory as a single artifact to restore it later. This should contain all the .class files needed.

Given that a similar artifact will be very large I'm afraid it could fill up the storage space pretty quickly so I'll investigate the possibility to delete it right away without having to wait 24 hours for its expiration.

Stay tuned!

**Comment by armandino** [comment]
@EvaristeGalois11 to give us more time to investigate, I temporarily reverted the build workflow to the previous revision.

**Comment by armandino** [comment]
@EvaristeGalois11 looks good now! :rocket: Could try submitting a test PR from you fork?

**Pull request closed without merging**
